### PR TITLE
Ansible 2.4 fixes

### PR DESCRIPTION
**Pull request by tiggi**
Miimal fixes for ansible 2.4

### CODE REVIEW

**Comment by jabl** [comment]
In general, should we use import_tasks or include_tasks?  Some docs at https://docs.ansible.com/ansible/latest/playbooks_reuse.html 

Do we need dynamic include (i.e. include_tasks) because we have the conditional to include based on distro?

**Comment by tiggi** [comment]
There is a slight difference if doing the include in a loop. But we don't.

**Comment by jabl** [comment]
Right, so could we use import_tasks instead then? If that works it sounds simpler and faster than having to evaluate the condition over and over again?

**Comment by tiggi** [comment]
It's still evaluated only once. If you have a loop around the include/import the semantics change.
I haven't found any of those in the fgci ansible ecosystem.

**Comment by jabl** [comment]
Yeah, makes sense..

**Comment by jabl** [comment]
Tagged v1.2.4 with this change. Thanks!

**Pull request merged**
